### ISSUE TITLE
Database list not showing

### ISSUE THREAD

**Issue by deep1931** [JoshyFrancis/mysql_backup_restore_php#1]
Hello, 
I am using your script but it is not showing databases list, neither in mamp nor on live server. What can be the issue. Please reply.

**Comment by JoshyFrancis** [comment]
Firstly , sorry for being late to reply. Have you given **$host,$port etc. definitions** correctly? Note that your **database user must have permissions to list/show the databases in server**. 
                                      Awaiting your reply. 
                                                                         best regards.
